### ISSUE TITLE
请问淘宝是不是改了sign的获取方式，我用你这个方法 一直显示非法请求

### ISSUE THREAD

**Issue by pythonL123** [jiaoyanfei/taobao-sign#1]
...

**Comment by jiaoyanfei** [comment]
这个方法淘宝系api用的比较广泛，推测他们改掉的可能性很低，因为改掉的成本很高，但不确定，可能是你用法不对，我们当时使用没问题，现在已经离职了，但是前公司系统貌似正常运转说明还在用，我QQ：911306137

**Comment by pythonL123** [comment]
嗯 的确是我的问题，少了一个符号，非常感谢..

**Comment by jiaoyanfei** [comment]
不客气，解决了就好
